#!/usr/bin/env python3
import requests
import re
import json
import sys

BASE = 'https://www.wordsapi.com'

def get_params():
    html = requests.get(BASE).text
    when = re.search("var when = '(.*?)';", html).group(1)
    encrypted = re.search("var encrypted = '(.*?)';", html).group(1)
    return {'when': when, 'encrypted': encrypted}

def get_definition(word):
    url = '{}/mashape/words/{}'.format(BASE, word)
    return requests.get(url, params=get_params()).json()

word = ' '.join(sys.argv[1:])
data = get_definition(word)

print('Word definition for', word)
print()
for result in data['results']:
    print(word, '·', result['partOfSpeech'])
    print('-', result['definition'])
