#!/usr/bin/env python3
import requests
import sys

word = ' '.join(sys.argv[1:])

url = 'https://api.urbandictionary.com/v0/define'
data = requests.get(url, params={'term': word}).json()

i = 0
for dfn in data['list'][:3]:
    print(dfn['definition'])
    print(dfn['example'])
    print('==============')
