#!/usr/bin/env python3
import requests
import sys

url = 'https://api.duckduckgo.com/?format=json&pretty=1&no_redirect=1'
query = ' '.join(sys.argv[1:])
query = '!w {}'.format(query)

data = requests.get(url, params={'q': query}).json()
print('Here\'s your Wikipedia link:', data['Redirect'])
